### ISSUE TITLE
Wrong answers

### ISSUE THREAD

**Issue by ivana1701** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#1]
Hi,
it would be great if the questions with answers would also be numbered (like in the table of content).
Also, I have noticed some question have wrong answers:

When is the Sprint backlog being created?
Correct answer: During the Sprint Planning Meeting.

A Scrum Master is essentially the same thing as a traditional PM.
Correct answer: False.

The Product OWner is not collaborating with the development team during the sprint. What are twovaluable actions froma a Scrum Master to take?
Correct answer: Bring the problem in the Sprint retrospective.
Coach the product owner in the values of Scrum and incremental delivery.

Five new Scrum Teams have been created to build one product. A few of the developers on one of the Development Teams ask the Scrum Master how to coordinate their work with the order teams. What should the Scrum Master do?
Correct answer: Teach them that it is their responsibility to work with the other teams to create an integrated increment.

**Comment by NikitaIT** [comment]
And this:

### Which statement best describes the Sprint Review? (choose the best answer)
- [x] It is when the Scrum Team and stakeholders inspect the outcome of a Sprint and figure out what to do next.

**Comment by danieldanielecki** [comment]
I'll look into the wrong answers, but questions definitely won't be numbered due to [Udemy format](https://www.udemy.com/course/professional-scrum-master-i-psm-i-practice-tests-exams/?referralCode=AE50158A452A3EAB8A7E) we need to upload them faster.

That's why questions have hyperlinks, so you can access each by clicking a link.

**Comment by danieldanielecki** [comment]
It has been incorporated in #2 and https://github.com/Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers/commit/2d7e6ae460f8b641055af2d3137f0fcb7fca7cac; thank you very much for contribution!
