### ISSUE TITLE
Incorrect answer: Who creates the definition of "Done"?

### ISSUE THREAD

**Issue by BorislavValov** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#13]
The answer to "Who creates the definition of "Done" is incorrect.

[Quoting the latest scrum guide:](https://www.scrum.org/learning-series/definition-done/frequently-asked-questions-about-being-done/who-creates-the-definition-of-done-)

> The answer to this question depends on whether the organization has already created a DoD for their products. If that’s the case, the Developers on your Scrum Team are required to conform to that DoD at a minimum. Your team is always welcome to add more stringent standards, but you may not make them more lax.
> 
> If no organizational DoD exists, the Scrum Team is obligated to create one for their product so that the Scrum Team and stakeholders are all clear on what it means for the Increment to be done. This should be one of the first things a Scrum Team does together.
> 
> If multiple Scrum Teams are working together on the same product, they must integrate their Increments together and the result must comply with the same Definition of Done.

Current question and answer:

Who creates the definition of "Done"?
 - The Scrum Master as he/she is responsible for the Development Team's productivity.
 - The Scrum Team, in a collaborative effort where the result is the common denominator of all members' definition.
 - The Product Owner as he/she is responsible for the product's success.
 - X **The development organization (or Development Team if none is available from the development organization).**

**Comment by danieldanielecki** [comment]
It's aligned with what you're quoting.
The development organization is creating it, as per the first paragraph ;-)

The remaining 3 answers are definitely not correct.
