### ISSUE TITLE
Why should the Product Owner be present at the Daily Scrum? (choose the best answer)

### ISSUE THREAD

**Issue by swotiendang** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#14]
Link: https://github.com/Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers?tab=readme-ov-file#why-should-the-product-owner-be-present-at-the-daily-scrum-choose-the-best-answer

Why should the Product Owner be present at the Daily Scrum? (choose the best answer)
- [ ] He/She doesn't need to be there.
- [ ] To hear about impediments in functionality.
- [ ] To represent the stakeholder's point of view.
- [ ] To participate as a Scrum Team member.

I believe for this question, answer should be b) To hear about impediments in functionality. It answers directly to the question why should, not by avoid the answer.

**Comment by danieldanielecki** [comment]
The answer is correct, PO doesn't need to be there.

Long discussion about this: https://www.scrum.org/forum/scrum-forum/6715/product-owner-allowed-participate-daily-scrum
CourseHero on this question: https://www.coursehero.com/file/p32rocm5/Why-should-the-Product-Owner-be-present-at-the-Daily-Scrum-Why-should-the/
