### ISSUE TITLE
update one question

### ISSUE THREAD

**Issue by jollin-george** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#15]
Who creates the Definition of Done?

A.
The Product Owner since they are responsible for the product's success.
B.
If it is not an organizational standard, the Scrum Team must create a Definition of Done appropriate for the product.
C.
The Scrum Master since they are responsible for the productivity of the Developers.
D.
The Scrum Team, in a collaborative effort where the result is the common denominator of all members' definitions.

answer is B

**Comment by danieldanielecki** [comment]
@jollin-george kindly please submit a pull request with the suggested changes :)

**Comment by danieldanielecki** [comment]
Disagree, based on:
- https://pupuweb.com/scrum-psm-i-qampa-who-creates-definition-done/
