### ISSUE TITLE
Wrong Answer - 186

### ISSUE THREAD

**Issue by Pedro-Costa123** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#5]
On the question 186 - Among the Developers, there is nobody with significant testing expertise. They should...(pick 2)
I found on www.thescrummaster.co.uk a different answer.
<img src="https://github.com/Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers/assets/102796961/3f7ba7f0-2f3d-4375-b488-ddc3637bf21d" weight=500 height=500 />

**Comment by danieldanielecki** [comment]
@Pedro-Costa123, it's in my backlog to check it out. Why have you closed this issue? Is it no longer relevant?

**Comment by Pedro-Costa123** [comment]
I found a lot more sources that agree with the answer you gave, instead of this one.

**Comment by Pedro-Costa123** [comment]
I found  more sources that agree with the answer you gave, instead of this one.

**Comment by danieldanielecki** [comment]
@Pedro-Costa123, many thanks for the quick, close-to-real-time answer.
Unfortunately, I can't address issues that quickly given the fact it's after hours activity and number of tests grows:)

Much appreciate your input and will be looking to seeing you around!
