### ISSUE TITLE
Duplicated question

### ISSUE THREAD

**Issue by mobidroid92** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#6]
Questions 66 and 224 are duplicates (Which statement best describes a Product Owner's responsibility?)

**Comment by danieldanielecki** [comment]
Thanks @mobidroid92, fixed in https://github.com/Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers/commit/2cdefd2bd9882fc84534c50dcd8b40481641c30b. One of the questions was indeed referring to an outdated term.
