### ISSUE TITLE
Typo in one of the answers

### ISSUE THREAD

**Issue by mobidroid92** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#8]
Question 104: The Daily Scrum is an event that happens every day. What would be three key concerns if the frequency were to be lowered to every two or three days?

Answer: Opportunities to "insect" and adapt the Sprint Backlog are lost.

"insect" should be "inspect"

**Comment by danieldanielecki** [comment]
Thanks @mobidroid92, fixed in https://github.com/Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers/commit/f9625500bfd63bf7b6d6b36845a98f060902cf2d
