### ISSUE TITLE
Typo in one of the questions

### ISSUE THREAD

**Issue by mobidroid92** [Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers#9]
Question 114: What "it" the main reason for the Scrum Master to be at the Daily Scrum?

"it" should be "is"

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Professional-Scrum-Master-I-PSM-I-Practice-Tests-Exams-Questions-Answers/commit/131ae23b32dca63681b3f4ec8b7c874d9435e573.
